### ISSUE TITLE
第九章

### ISSUE THREAD

**Issue by Oldzzzzz** [datawhalechina/d2l-ai-solutions-manual#25]
求第九章的答案 跪谢🙇‍♂️

**Comment by Rookie-Kai** [comment]
> 求第九章的答案 跪谢🙇‍♂️

您好，感谢关注，第九章的习题目前正在完善中，我们会尽快上传第九章的习题解答

**Comment by Rookie-Kai** [comment]
> 求第九章的答案 跪谢🙇‍♂️
您好，目前第九章习题已更新完毕，如有问题还请多多指出

**Comment by Oldzzzzz** [comment]
> > 求第九章的答案 跪谢🙇‍♂️
> > 您好，目前第九章习题已更新完毕，如有问题还请多多指出

十分感谢！特别及时！跪谢真的

**Comment by Oldzzzzz** [comment]
> > 求第九章的答案 跪谢🙇‍♂️
> > 您好，目前第九章习题已更新完毕，如有问题还请多多指出

能不能顺便更新下8.5.3的答案 有些没搞清楚题意😂
