### ISSUE TITLE
3.1. 线性回归答案的一些想法

### ISSUE THREAD

**Issue by fire-lit-band** [datawhalechina/d2l-ai-solutions-manual#33]
3.1.1
第一问的证明办法有点麻烦，直接对b求导，我们可以得到
$\sum 2(b-x_i)=0$展开后可以直接得到最后的结果
然后第二问我感觉描述有点混乱，我的建议改成：
对于一个正态分布的总体，取n次样本 $x_1, \dots  x_n $，此时得到的样本平均数为 $\bar x$，根据大数定理，在取较多的样本，也就是n比较大的时候, $b=\bar x$会趋近于正态分布的期望（或者中心）
3.1.2
“多个局部最小值”的说法不成立，算一下Hessian可以知道解析解应该是global minimum($X^TX$是半正定矩阵），

**Comment by catcooc** [comment]
你是对的，感谢提供想法和建议 ，我们会进行相应修改

**Comment by Ethan-Chen-plus** [comment]
@fire-lit-band  后续会提供修改，请持续关注，有问题欢迎随时提出。
