### ISSUE TITLE
公式推导问题

### ISSUE THREAD

**Issue by YUFEIFUT** [datawhalechina/d2l-ai-solutions-manual#43]
![image](https://github.com/datawhalechina/d2l-ai-solutions-manual/assets/55017929/18950c83-34fc-47c0-b6c3-2e23e4cb1240)
请问这里是不是写反了呢，感觉应该是 b - x_i 才对啊

**Comment by Ethan-Chen-plus** [comment]
后面纠正一下，谢谢指正

**Comment by YUFEIFUT** [comment]
好的

**Comment by YUFEIFUT** [comment]
话说我提个 PR 可以不罗
